# Generated by Django 4.2.5 on 2023-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0002_products_net_alter_products_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='net',
        ),
        migrations.AlterField(
            model_name='products',
            name='delivery',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
